// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDHaj45tcbinFTi3IkL_4gzEIS60BhTZHY',
    appId: '1:301098433056:web:54587b5127bbbbe9aa1a45',
    messagingSenderId: '301098433056',
    projectId: 'wordle-a94fa',
    authDomain: 'wordle-a94fa.firebaseapp.com',
    storageBucket: 'wordle-a94fa.appspot.com',
    measurementId: 'G-FNDM3PHEEC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC6kFcure4fgu7ws7M32m9Wq8QL1kVVAkY',
    appId: '1:301098433056:android:9feaeb2ba03372a6aa1a45',
    messagingSenderId: '301098433056',
    projectId: 'wordle-a94fa',
    storageBucket: 'wordle-a94fa.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCHKUhCEo04q9ShzTsYJHuxBMngiZ1J3BQ',
    appId: '1:301098433056:ios:d181f5483bccd267aa1a45',
    messagingSenderId: '301098433056',
    projectId: 'wordle-a94fa',
    storageBucket: 'wordle-a94fa.appspot.com',
    iosBundleId: 'com.example.wordle',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCHKUhCEo04q9ShzTsYJHuxBMngiZ1J3BQ',
    appId: '1:301098433056:ios:3c06f1d35174eb41aa1a45',
    messagingSenderId: '301098433056',
    projectId: 'wordle-a94fa',
    storageBucket: 'wordle-a94fa.appspot.com',
    iosBundleId: 'com.example.wordle.RunnerTests',
  );
}
